image: "rustdocker/rust:nightly"

# Use cargo to build the project
build:cargo:
    stage: build
    script:
        - cargo build --verbose --jobs 1 --release # Don't paralize to make errors more readable

# Use carge to test the project
test:cargo:
    stage: test
    script:
        - cargo test --verbose --jobs 1 --release  # Don't paralize to make errors more readable
