image: "rustdocker/rust:nightly"

# Use cargo to build the project
build:cargo:
    stage: build
    before_script:
        - which ssh-agent || ( apt-get update -y && apt-get install openssh-client git curl -y )
        - eval `ssh-agent -s`
        - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    script:
        - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" cargo build --verbose --jobs 1 --release # Don't paralize to make errors more readable
        - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" cargo test --verbose --jobs 1 --release  # Don't paralize to make errors more readable
    

