image: "rustdocker/rust:nightly"

# Use cargo to build the project
build:cargo:
    stage: build
    before_script:
        - apt-get update
        - apt-get install -y git curl openssh-client bash
        - eval $(ssh-agent -s)
        - mkdir ~/.ssh; echo '$DEPLOY_SSH_KEY' > ~/.ssh/id_rsa; chmod 0644 ~/.ssh/id_rsa
        - eval `ssh-agent -s`
        - ssh-add
    script:
        - cargo build --verbose --jobs 1 --release # Don't paralize to make errors more readable
        - cargo test --verbose --jobs 1 --release  # Don't paralize to make errors more readable
    

