image: "rustdocker/rust:nightly"

# Use cargo to build the project
build:cargo:
    stage: build
    before_script:
        - apt-get update
        - apt-get install -y git curl openssh-client bash
        - ssh-add <(echo '$DEPLOY_SSH_KEY')
        - eval $(ssh-agent -s)
    script:
        - cargo build --verbose --jobs 1 --release # Don't paralize to make errors more readable
        - cargo test --verbose --jobs 1 --release  # Don't paralize to make errors more readable
    

