image: "rustdocker/rust:nightly"

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: rabe # Created at image startup
  MYSQL_ROOT_PASSWORD: passwd

# Use cargo to build the project
build:cargo:
    stage: build
    before_script:
        - apt-get update -qq && apt-get install -y libmysqlclient-dev mysql-client libsqlite3-dev libpq-dev
        - if ! type diesel > /dev/null; then cargo install diesel_cli --force; fi #install diesel if not installed
        - which ssh-agent || ( apt-get update -y && apt-get install openssh-client git curl -y )
        - eval `ssh-agent -s`
        - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    script:
        - diesel migration run
        - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" cargo build --jobs 1 # Don't paralize to make errors more readable
        - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" RUST_BACKTRACE=1 DATABASE_URL=mysql://root:passwd@mysql/rabe cargo test --jobs 1  # Don't paralize to make errors more readable
    

