theme = "docuapi"
themesdir = "themes"
languageCode = "en-us"
baseurl = "http://www.aisec.fraunhofer.de/"
title = "R-ABE Keyserver API"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "shell"
name = "Shell" 
[[params.language_tabs]]
key = "python"
name = "Python"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "R-ABE Keyserver API"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"Provided by Fraunhofer AISEC",
"",
""
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true


[languages.de]
languageName = "Deutsch"
weight = 1
title = "R-ABE"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='#'>Registrer deg for ein utviklarnøkkel</a>",
"Dokumentasjonen er driven av [DocuAPI](https://github.com/bep/docuapi)",
"Hugo Theme av [bep](https://github.com/bep)"
]

[languages.nn.blackfriday]
# Norwegian uses angled quotes
angledQuotes = true
hrefTargetBlank = true